### ISSUE TITLE
Umm da website dusnt work

### ISSUE THREAD

**Issue by PengiCoder** [MrPiggy105/Penguin#2]
Can @MrPiggy105 fix it

**Comment by MrPiggy105** [comment]
More detail pls

**Comment by MrPiggy105** [comment]
It works to deploy it with static.app because I did it at https://pengicoder-penguin.static.domains/

(also if you have a Telstra or school internet it's probably blocked because they both think it's unsafe)

**Comment by MrPiggy105** [comment]
By the way, huge overhaul to README.markdown coming

**Comment by MrPiggy105** [comment]
Ok… I’ll make an action to deploy from the vue build, but you need to send me your token
